---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1m
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.sh
  interval: 10m
  url: https://code.il5.dso.mil/cnap/cubbyhole.git
  ref:
    branch: production-live