---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vault-deploy
  namespace: vault
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: vault
    namespace: vault
  path: "./env/prod/"
  prune: true
  decryption:
    provider: sops