{{- if and .Values.istio.enabled .Values.autoInit.enabled (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: vault-autoinit-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  portLevelMtls:
    "8200":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
{{- end }}
