{{- if .Values.istio.enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: vault-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  portLevelMtls:
    "8080":
      mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
{{- end }}
