{{ if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-custom-selector
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          {{ .Values.customAppIngressSelector.key }}: "{{ .Values.customAppIngressSelector.value }}"
    ports:
    - protocol: TCP
      port: {{ .Values.injector.port }}
    - protocol: TCP
      port: {{ .Values.server.service.port }}
{{- end }}
