creation_rules:
    # when adding DNSSEC keys use this file to encrypt and decrypt key data 
    - path_regex: .*/bigbang/*
      kms: 'arn:blah' # stg
      encrypted_regex: '^(data|stringData)$' 
    - path_regex: .*/vault/*
      kms: 'arn:aws-us-gov:kms:us-gov-west-1:235668867212:key/c5566fd8-0942-4463-99d3-c06ac4bdb2da' # stg
      encrypted_regex: '^(data|stringData)$'