apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: private-registry
    namespace: vault
data:
    .dockerconfigjson: ENC[AES256_GCM,data:RcFHj+OI/LV3oaNb0g0XqP8k+fxubRF1GOrinfV08u9ceOYSGk0/Vwd7OvhqPj3IqpxLIatMYqAIaJI60HXnldb59JbXzAiW5c1ESeL7kKOkRSzty9enZ+IpqMCUmsIZVZ0KR65XL5zS61rmi3J+eoFZM6kDe9qc7T6mRz7zi6XaLV5mWk+9xp/sSYGsIuIYC7v0sMzOIq0nSPKQnbtTszNjfYwm3Jz4f7Z8sE9F3WBuhfmZSHdqFwEBhnsMbGhVZ0V91vpn4CKmtaSR1Egs8MlA2K8GoLbL,iv:utB++xjyLawOZqTEioZ+mgWVEG7h/SOc60MEvxWh30g=,tag:59kv/I6iyU1m0rCSJ2OqIg==,type:str]
sops:
    kms:
    -   arn: arn:aws-us-gov:kms:us-gov-west-1:235856440647:key/d9a89538-efd8-4ade-a5b6-dcc99c8ec471
        created_at: '2021-01-09T00:17:19Z'
        enc: AQICAHj5uxElsHNrNY8sj6W2uPCKgVzRyCNoJcYjbNSX7C3nAwGwjbDD9YnYl29pjhslaWvlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYZ6m9qmeJWhDyMJiAgEQgDvgqBcI9pURHPVkuwfOdAnYbS42PnobNVc3HiKAW0+M8MLMAa0AXEKEbTzrhhpWtwbSV5Aut+1tGHy92A==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-09T00:17:19Z'
    mac: ENC[AES256_GCM,data:ESB1mkXCfWSu/lQzgPUB1wcKosdFw/DhDT2v3uo6VGRczRFitM+8jAMA0NCO7H/3YH2sqOS5bwsUcgVjKFY5Urx9/WVV85KubRwfwwhybnrzzFIkQeQZq1oZ1RKRm5rKcVm+BkTGj007hvLppMTDMafqlhNSlD0cI2UzW+LUeH4=,iv:r/0fSpZamGSnOpooRiIjx8gRfP4OFr/iW6papV8DOPE=,tag:2BQHyzJs+TCxmu1dOFYyug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
