---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: this
  namespace: bigbang
spec:
  interval: 1m0s
  url: https://code.il5.dso.mil/cnap/cubbyhole.git
  ref:
    branch: production-live
  secretRef:
    name: repo-credential

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: bigbang
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: this
    namespace: bigbang
  path: "./deploy/prod/bb-umbrella/secrets"
  prune: true
  decryption:
    provider: sops
