{{- if and .Values.autoInit.enabled .Release.IsInstall }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "vault.fullname" . }}-token-claim
  namespace: {{ .Release.Namespace }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.autoInit.storage.size }}
{{- end }}
