{{- if  .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: vault
spec:
  gateways:
  {{- range .Values.istio.vault.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.vault.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
      - destination:
          port:
            number: 8200
          host: {{ .Release.Name }}.vault.svc.cluster.local

{{- end }}