apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "vault.fullname" . }}-root-token-secret
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-root-token-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  - secrets
  verbs:
  - create
  - get
  - watch
  - list