apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "vault.fullname" . }}-root-token-secret
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-root-token-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "vault.fullname" . }}-root-token-secret
subjects:
- kind: ServiceAccount
  name: {{ template "vault.fullname" . }}-root-token-secret
  namespace: {{ .Release.Namespace }}