apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}-job-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      containers:
      - name: vault-init-job
        image:  {{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
        command: ['/bin/sh', '-c', 'cd /vault/data/init && sh init.sh' ]
        volumeMounts:
        - name: vault-keys
          mountPath: "/vault/data"
        - name: vault-data
          mountPath: "/vault/data/init"
      restartPolicy: OnFailure
      serviceAccount: vault
      volumes:
      - name: vault-keys
        persistentVolumeClaim:
          claimName: {{ template "vault.fullname" . }}-token-claim
      - name: vault-data
        configMap:
          name: vault-init-cm
  backoffLimit: 10
  activeDeadlineSeconds: 360
