apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault.fullname" . }}-root-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-root-token-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}