---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: this
  namespace: fluentbit
spec:
  interval: 1m0s
  url: https://code.il2.dso.mil/cnap/vault-dev.git
  ref:
    branch: fluentbit
  secretRef:
    name: repository-credentials

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: fluentbit
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: this
    namespace: bigbang
  path: "./deploy/dev/secrets"
  prune: true
  decryption:
    provider: sops
