apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  owner: vault

# Adds namespace to all resources.
namespace: vault

bases:
  - ../../base
  - ./secrets

resources:
  - virtualservice.yaml
  - peerauth.yaml
  - ./hsm-client

patchesStrategicMerge:
  - patch-values.yaml
  - gitrepository.yaml
  