---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  # Increase reconciliation interval for dev
  interval: 1m0s
  valuesFrom:
  - name: vault-values
    kind: Secret
    optional: true
  values:

    # Vault Helm Chart Value Overrides
    global:
      enabled: true
      tlsDisable: true
      imagePullSecrets:
        - name: private-git-registry
        
    injector:
      enabled: false
      # Use the Vault K8s Image https://github.com/hashicorp/vault-k8s/
      image:
        repository: "hashicorp/vault-k8s"
        tag:  v0.6.0

      resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
       
    server:

      # the following annotations are requied to exempt traffic from the raft protocol 
      # otherwise, envoy side-car will interrupt raft-member to raft-member tls communications
      annotations:  
        traffic.sidecar.istio.io/excludeInboundPorts: "8201"
        traffic.sidecar.istio.io/excludeOutboundPorts: "8201"
      image:
        # Enterprise Image - license required
        # repository: "hashicorp/vault-enterprise"
        # tag: "1.6.1_ent"
        # tag: "1.5.0_ent" 

        # Non-Enterprise - no license required
        # repository: "hashicorp/vault"
        # tag: "1.6.1"

        # Custom IB UBI8 Vault + HSM - in house 
        # repository: registry.il2.dso.mil/cnap/vault-dev/hsm-vault
        # tag: latest
        # pullPolicy: Always

        # Custom IB UBI8 Vault + HSM - hashi offical
        repository: registry.il2.dso.mil/cnap/vault-dev/vault_ent_hsm_ib
        tag: v1.6.1
        pullPolicy: Always
        
      # The Following Resource Limits are in line with node requirements in the
      # Vault Reference Architecture for a Small Cluster

      # PROD
      # resources:
      #   requests:
      #     memory: 8Gi
      #     cpu: 2000m
      #   limits:
      #     memory: 16Gi
      #     cpu: 2000m

      # DEV
      resources:
        requests:
          memory: 2Gi
          cpu: 250m
        limits:
          memory: 4Gi
          cpu: 500m

      ingress:
        enabled: false

      # For HA configuration and because we need to manually init the vault,
      # we need to define custom readiness/liveness Probe settings
      readinessProbe:
        enabled: false
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204" #orinal setting
      livenessProbe:
        enabled: false
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60

      # extraEnvironmentVars is a list of extra enviroment variables to set with the stateful set. These could be
      # used to include variables required for auto-unseal.
      extraEnvironmentVars:
        # VAULT_API_ADDR:  http://$(HOSTNAME).vault-internal:8200
        #VAULT_CLUSTER_ADDR:  http://$(HOSTNAME).vault-internal:8201
        # VAULT_CLUSTER_ADDR:  http://127.0.0.1:8201
        VAULT_API_ADDR: http://vault-internal:8200
        VAULT_ADDR:  http://127.0.0.1:8200

      # extraVolumes is a list of extra volumes to mount. These will be exposed
      # to Vault in the path `/vault/userconfig/<name>/`.
      extraVolumes:
        - type: configMap
          name: cloudhsm-client-cfg
        - type: configMap
          name: cloudhsm-mgmt-util-cfg
        - type: secret
          name: customer-ca-crt
        - type: secret
          name: cloudhsm-client-crt

      volumeMounts:
        - name: userconfig-cloudhsm-client-cfg
          mountPath:  /opt/cloudhsm/etc/cloudhsm_client.cfg
          subPath: cloudhsm_client.cfg
        - name: userconfig-cloudhsm-mgmt-util-cfg
          mountPath:  /opt/cloudhsm/etc/cloudhsm_mgmt_util.cfg
          subPath: cloudhsm_mgmt_util.cfg
        - name: userconfig-customer-ca-crt
          mountPath:  /opt/cloudhsm/etc/customerCA.crt
          subPath: customerCA.crt
        - name: userconfig-customer-ca-crt
          mountPath:  /opt/cloudhsm/etc/certs/4395fb20.0
          subPath: customerCA.crt
        - name: userconfig-cloudhsm-client-crt
          mountPath:  /opt/cloudhsm/etc/ssl-client.crt
          subPath: tls.crt
        - name: userconfig-cloudhsm-client-crt
          mountPath:  /opt/cloudhsm/etc/ssl-client.key
          subPath: tls.key

      # This configures the Vault Statefulset to create a PVC for audit logs.
      # See https://www.vaultproject.io/docs/audit/index.html to know more
      auditStorage:
        enabled: true

      # Run Vault in "HA" mode.
      ha:
        enabled: true
        replicas: 5

        raft:
          enabled: true
          setNodeId: true

          # config file encrypted in vault-values.enc.yaml 

    # Vault UI
    ui:
      enabled: true
      serviceType: "ClusterIP"
      serviceNodePort: null
      externalPort: 8200