apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault
spec:
  gateways:
  - main.istio-system.svc.cluster.local
  hosts:
  - vault.cnap.dev
  http:
  - route:
    - destination:
        host: vault
        port:
          number: 8200