---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  url: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/cert-manager