---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vault-deploy
  namespace: vault
spec:
  interval: 5m0s
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: vault-deploy
    namespace: vault
  path: "./envs/dev/"
  prune: true
  decryption:
    provider: sops