{{- if .Values.monitoring.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
{{- end }}
