apiVersion: v1
kind: Service
metadata:
  annotations:
  name: prometheus-service
  labels:
    helm.sh/chart: {{ template "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9125
    protocol: TCP
    targetPort: 9125
  selector:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  sessionAffinity: None
  type: ClusterIP
