{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      name: vault
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - interval: 30s
      path: /v1/sys/metrics
      params:
        format: 
          - prometheus
      port: '8200'
      scheme: http
      tlsConfig:
        insecureSkipVerify: true 
      bearerTokenSecret: 
         name: vault-token
         key: data
  jobLabel: vault-metrics
{{- end }}
